name: Ejercicio 2 - Push a Main

# Aquí se configura lo que pide la imagen: el evento push a la rama main
on:
  push:
    branches:
      - main

jobs:
  verificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mensaje de exito
        run: echo "El workflow se ejecuto correctamente tras un push a la rama main."